### ISSUE TITLE
Does it affect SEO?

### ISSUE THREAD

**Issue by akroii** [nathansmith/adapt#32]
In some cases search engines can't read css files which included dynamically. Does it apply to adapt.js too? It is important to make accessible those files.

**Comment by nathansmith** [comment]
It shouldn't negatively impact SEO, as long as what's in the CSS files isn't setting things to `display: none`.

Though, really, Adapt.js is a dinosaur. It's a relic, from when versions of IE (that were prevalent at the time) didn't support `@media` queries.

As of IE9 and newer, Adapt.js shouldn't even be necessary to use. I mean, it still works, but the problem it attempted to solve has long since ceased being a problem.

**Comment by msigley** [comment]
@nathansmith Adapt is still the easiest solution for javascript resizing that needs to be done when the viewport changes.
