### ISSUE TITLE
Zooming on iPhone, iPad 

### ISSUE THREAD

**Issue by weschyrchel** [nathansmith/adapt#5]
Nathan,

I noticed pinch zooming and tap zooming on iPhone and iPad is not functional on your Adapt demo site. Was this intentional or overlooked? Do you have any recommendations on how to enable it with your code?

Thank you!

Wes

**Comment by nathansmith** [comment]
Wes: That's due to a meta tag in the HTML...

```
<meta name="viewport" content="width=device-width; initial-scale=1; minimum-scale=1; maximum-scale=1" />
```

To enable zooming, change that to...

```
<meta name="viewport" content="width=device-width; initial-scale=1" />
```

**Comment by weschyrchel** [comment]
Nathan,

Thank you so much!

I actually had two more questions if you wouldn't mind,
1.  What are the "min" versions of the files for in the css directory under
   "code" and the ".min.css" in the /assets/css/ directories?
2.  Under Grid 960, do I need the "_rtl" versions in the css and min
   directories?

Thanks again for all of your work. It looks great.

Wes

**Comment by nathansmith** [comment]
Wes:

The *.min.css and *.min.js files have the same code, just with all unnecessary whitespace and indentation removed. It helps the browser download the files faster, because it doesn't care about whitespace (which exists only for human readability). Same with the "/min" directory.

The *_rtl.css files are for Right-To-Left languages. So unless you're doing a site in Hebrew, Arabic, or some other language that reads from right to left, you don't need them. I know there are quite a bit of files, but feel free to delete any files that you don't deem applicable to your project.

**Comment by weschyrchel** [comment]
Thanks Nathan!

**Comment by weschyrchel** [comment]
Hey Nathan,

Really, last question.

If I would like to use your Adapt.js, would I only need to link to
master.css and not link to 960.css or just add in your script and it will
take care of choosing the correct stylesheet?

Sorry for all the questions.

Thanks,

Wes

**Comment by weschyrchel** [comment]
Okay, I think I get it.  Just use the script.

**Comment by nathansmith** [comment]
Wes:

Yeah, adapt.js can be used to serve any stylesheets conditionally based on browser width. If you wanted to go crazy and make each width have a different background color, via a separate CSS file, you could.

You needn't use any of the grid CSS files if you don't want to. The accompanying files that come with Adapt.js are just suggestions, feel free to discard and serve whatever CSS files you like. :)

**Comment by weschyrchel** [comment]
Thanks again Nathan!
